// Generated by scripts/gen-types.mjs — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      acknowledgements: {
        Row: {
          id: string;
          work_order_id: string;
          vehicle_id: string;
          template_version: string;
          body: string;
          signer_name: string;
          signed_by: string | null;
          ip: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          vehicle_id: string;
          template_version: string;
          body: string;
          signer_name: string;
          signed_by?: string | null;
          ip?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          vehicle_id?: string;
          template_version?: string;
          body?: string;
          signer_name?: string;
          signed_by?: string | null;
          ip?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'acknowledgements_signed_by_fkey';
            columns: ['signed_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'acknowledgements_vehicle_id_fkey';
            columns: ['vehicle_id'];
            isOneToOne: false;
            referencedRelation: 'vehicles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'acknowledgements_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      appointments: {
        Row: {
          id: string;
          customer_id: string;
          vehicle_id: string | null;
          work_order_id: string | null;
          service_id: string | null;
          service_label: string;
          starts_at: string;
          ends_at: string;
          status: Database['public']['Enums']['appointment_status'];
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          vehicle_id?: string | null;
          work_order_id?: string | null;
          service_id?: string | null;
          service_label: string;
          starts_at: string;
          ends_at: string;
          status?: Database['public']['Enums']['appointment_status'];
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          vehicle_id?: string | null;
          work_order_id?: string | null;
          service_id?: string | null;
          service_label?: string;
          starts_at?: string;
          ends_at?: string;
          status?: Database['public']['Enums']['appointment_status'];
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'appointments_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'appointments_vehicle_id_fkey';
            columns: ['vehicle_id'];
            isOneToOne: false;
            referencedRelation: 'vehicles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'appointments_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      approvals: {
        Row: {
          id: string;
          work_order_id: string;
          signer_name: string;
          signed_by: string | null;
          approved_item_ids: string[];
          declined_item_ids: string[];
          approved_total_cents: number;
          snapshot: Json;
          snapshot_sha256: string;
          ip: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          signer_name: string;
          signed_by?: string | null;
          approved_item_ids?: string[];
          declined_item_ids?: string[];
          approved_total_cents: number;
          snapshot: Json;
          snapshot_sha256: string;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          signer_name?: string;
          signed_by?: string | null;
          approved_item_ids?: string[];
          declined_item_ids?: string[];
          approved_total_cents?: number;
          snapshot?: Json;
          snapshot_sha256?: string;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'approvals_signed_by_fkey';
            columns: ['signed_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'approvals_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      audit_log: {
        Row: {
          id: number;
          actor_id: string | null;
          entity: string;
          entity_id: string | null;
          action: string;
          data: Json;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          entity: string;
          entity_id?: string | null;
          action: string;
          data?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          entity?: string;
          entity_id?: string | null;
          action?: string;
          data?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'audit_log_actor_id_fkey';
            columns: ['actor_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      automation_runs: {
        Row: {
          id: string;
          automation_key: string;
          subject_type: string;
          subject_id: string | null;
          dedupe_key: string | null;
          context: Json;
          status: Database['public']['Enums']['automation_run_status'];
          scheduled_for: string;
          executed_at: string | null;
          detail: string | null;
          created_at: string;
          audience: string | null;
        };
        Insert: {
          id?: string;
          automation_key: string;
          subject_type: string;
          subject_id?: string | null;
          dedupe_key?: string | null;
          context?: Json;
          status?: Database['public']['Enums']['automation_run_status'];
          scheduled_for?: string;
          executed_at?: string | null;
          detail?: string | null;
          created_at?: string;
          audience?: string | null;
        };
        Update: {
          id?: string;
          automation_key?: string;
          subject_type?: string;
          subject_id?: string | null;
          dedupe_key?: string | null;
          context?: Json;
          status?: Database['public']['Enums']['automation_run_status'];
          scheduled_for?: string;
          executed_at?: string | null;
          detail?: string | null;
          created_at?: string;
          audience?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'automation_runs_automation_key_fkey';
            columns: ['automation_key'];
            isOneToOne: false;
            referencedRelation: 'automations';
            referencedColumns: ['key'];
          },
        ];
      };
      automations: {
        Row: {
          key: string;
          name: string;
          description: string;
          trigger_event: string;
          audience: string;
          channels: Database['public']['Enums']['message_channel'][];
          delay_minutes: number;
          enabled: boolean;
          sms_template: string | null;
          email_subject_template: string | null;
          email_body_template: string | null;
          sort: number;
          updated_at: string;
          anchor: string;
        };
        Insert: {
          key: string;
          name: string;
          description: string;
          trigger_event: string;
          audience: string;
          channels: Database['public']['Enums']['message_channel'][];
          delay_minutes?: number;
          enabled?: boolean;
          sms_template?: string | null;
          email_subject_template?: string | null;
          email_body_template?: string | null;
          sort?: number;
          updated_at?: string;
          anchor?: string;
        };
        Update: {
          key?: string;
          name?: string;
          description?: string;
          trigger_event?: string;
          audience?: string;
          channels?: Database['public']['Enums']['message_channel'][];
          delay_minutes?: number;
          enabled?: boolean;
          sms_template?: string | null;
          email_subject_template?: string | null;
          email_body_template?: string | null;
          sort?: number;
          updated_at?: string;
          anchor?: string;
        };
        Relationships: [

        ];
      };
      build_items: {
        Row: {
          id: string;
          vehicle_id: string;
          work_order_id: string | null;
          category: string;
          part_name: string;
          brand: string | null;
          installed_at: string | null;
          warranty_until: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          work_order_id?: string | null;
          category: string;
          part_name: string;
          brand?: string | null;
          installed_at?: string | null;
          warranty_until?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          work_order_id?: string | null;
          category?: string;
          part_name?: string;
          brand?: string | null;
          installed_at?: string | null;
          warranty_until?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'build_items_vehicle_id_fkey';
            columns: ['vehicle_id'];
            isOneToOne: false;
            referencedRelation: 'vehicles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'build_items_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      builds: {
        Row: {
          id: string;
          slug: string;
          title: string;
          vehicle_label: string;
          platform: string;
          summary: string;
          story: string | null;
          hero_image: string;
          before_hp: number | null;
          after_hp: number | null;
          before_torque: number | null;
          after_torque: number | null;
          parts: string[];
          published: boolean;
          is_sample: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          vehicle_label: string;
          platform: string;
          summary: string;
          story?: string | null;
          hero_image: string;
          before_hp?: number | null;
          after_hp?: number | null;
          before_torque?: number | null;
          after_torque?: number | null;
          parts?: string[];
          published?: boolean;
          is_sample?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          vehicle_label?: string;
          platform?: string;
          summary?: string;
          story?: string | null;
          hero_image?: string;
          before_hp?: number | null;
          after_hp?: number | null;
          before_torque?: number | null;
          after_torque?: number | null;
          parts?: string[];
          published?: boolean;
          is_sample?: boolean;
          created_at?: string;
        };
        Relationships: [

        ];
      };
      customers: {
        Row: {
          id: string;
          profile_id: string | null;
          full_name: string;
          email: string | null;
          phone: string | null;
          sms_consent: boolean;
          sms_consent_at: string | null;
          sms_consent_version: string | null;
          sms_opted_out_at: string | null;
          source: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          sms_consent?: boolean;
          sms_consent_at?: string | null;
          sms_consent_version?: string | null;
          sms_opted_out_at?: string | null;
          source?: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          sms_consent?: boolean;
          sms_consent_at?: string | null;
          sms_consent_version?: string | null;
          sms_opted_out_at?: string | null;
          source?: string;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'customers_profile_id_fkey';
            columns: ['profile_id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      dyno_runs: {
        Row: {
          id: string;
          vehicle_id: string;
          tune_record_id: string | null;
          work_order_id: string | null;
          label: string;
          is_baseline: boolean;
          horsepower: number | null;
          torque: number | null;
          boost_psi: number | null;
          egt_f: number | null;
          notes: string | null;
          sheet_path: string | null;
          run_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          tune_record_id?: string | null;
          work_order_id?: string | null;
          label: string;
          is_baseline?: boolean;
          horsepower?: number | null;
          torque?: number | null;
          boost_psi?: number | null;
          egt_f?: number | null;
          notes?: string | null;
          sheet_path?: string | null;
          run_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          tune_record_id?: string | null;
          work_order_id?: string | null;
          label?: string;
          is_baseline?: boolean;
          horsepower?: number | null;
          torque?: number | null;
          boost_psi?: number | null;
          egt_f?: number | null;
          notes?: string | null;
          sheet_path?: string | null;
          run_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'dyno_runs_tune_record_id_fkey';
            columns: ['tune_record_id'];
            isOneToOne: false;
            referencedRelation: 'tune_records';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'dyno_runs_vehicle_id_fkey';
            columns: ['vehicle_id'];
            isOneToOne: false;
            referencedRelation: 'vehicles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'dyno_runs_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      gallery_items: {
        Row: {
          id: string;
          title: string;
          caption: string | null;
          category: string;
          platform: string | null;
          vehicle_label: string | null;
          image_url: string;
          storage_path: string | null;
          width: number;
          height: number;
          build_id: string | null;
          sort: number;
          published: boolean;
          is_sample: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          caption?: string | null;
          category?: string;
          platform?: string | null;
          vehicle_label?: string | null;
          image_url: string;
          storage_path?: string | null;
          width?: number;
          height?: number;
          build_id?: string | null;
          sort?: number;
          published?: boolean;
          is_sample?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          caption?: string | null;
          category?: string;
          platform?: string | null;
          vehicle_label?: string | null;
          image_url?: string;
          storage_path?: string | null;
          width?: number;
          height?: number;
          build_id?: string | null;
          sort?: number;
          published?: boolean;
          is_sample?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'gallery_items_build_id_fkey';
            columns: ['build_id'];
            isOneToOne: false;
            referencedRelation: 'builds';
            referencedColumns: ['id'];
          },
        ];
      };
      inspection_items: {
        Row: {
          id: string;
          inspection_id: string;
          category: string;
          label: string;
          rating: Database['public']['Enums']['inspection_rating'];
          notes: string | null;
          sort: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          inspection_id: string;
          category: string;
          label: string;
          rating?: Database['public']['Enums']['inspection_rating'];
          notes?: string | null;
          sort?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          inspection_id?: string;
          category?: string;
          label?: string;
          rating?: Database['public']['Enums']['inspection_rating'];
          notes?: string | null;
          sort?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'inspection_items_inspection_id_fkey';
            columns: ['inspection_id'];
            isOneToOne: false;
            referencedRelation: 'inspections';
            referencedColumns: ['id'];
          },
        ];
      };
      inspections: {
        Row: {
          id: string;
          work_order_id: string;
          tech_id: string | null;
          status: Database['public']['Enums']['inspection_status'];
          summary: string | null;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          tech_id?: string | null;
          status?: Database['public']['Enums']['inspection_status'];
          summary?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          tech_id?: string | null;
          status?: Database['public']['Enums']['inspection_status'];
          summary?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'inspections_tech_id_fkey';
            columns: ['tech_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'inspections_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: true;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      invoices: {
        Row: {
          id: string;
          number: number;
          work_order_id: string;
          customer_id: string;
          subtotal_cents: number;
          tax_cents: number;
          total_cents: number;
          status: Database['public']['Enums']['invoice_status'];
          line_snapshot: Json;
          stripe_checkout_session_id: string | null;
          due_at: string | null;
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          number?: number;
          work_order_id: string;
          customer_id: string;
          subtotal_cents: number;
          tax_cents: number;
          total_cents: number;
          status?: Database['public']['Enums']['invoice_status'];
          line_snapshot?: Json;
          stripe_checkout_session_id?: string | null;
          due_at?: string | null;
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          number?: number;
          work_order_id?: string;
          customer_id?: string;
          subtotal_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          status?: Database['public']['Enums']['invoice_status'];
          line_snapshot?: Json;
          stripe_checkout_session_id?: string | null;
          due_at?: string | null;
          paid_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'invoices_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'invoices_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: true;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      leads: {
        Row: {
          id: string;
          customer_id: string | null;
          full_name: string;
          email: string;
          phone: string;
          platform: string | null;
          platform_label: string | null;
          mileage: string | null;
          service_id: string | null;
          service_label: string | null;
          details: string | null;
          sms_consent: boolean;
          consent_ip: string | null;
          status: Database['public']['Enums']['lead_status'];
          source: string;
          contacted_at: string | null;
          converted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id?: string | null;
          full_name: string;
          email: string;
          phone: string;
          platform?: string | null;
          platform_label?: string | null;
          mileage?: string | null;
          service_id?: string | null;
          service_label?: string | null;
          details?: string | null;
          sms_consent?: boolean;
          consent_ip?: string | null;
          status?: Database['public']['Enums']['lead_status'];
          source?: string;
          contacted_at?: string | null;
          converted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string | null;
          full_name?: string;
          email?: string;
          phone?: string;
          platform?: string | null;
          platform_label?: string | null;
          mileage?: string | null;
          service_id?: string | null;
          service_label?: string | null;
          details?: string | null;
          sms_consent?: boolean;
          consent_ip?: string | null;
          status?: Database['public']['Enums']['lead_status'];
          source?: string;
          contacted_at?: string | null;
          converted_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'leads_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          },
        ];
      };
      line_items: {
        Row: {
          id: string;
          work_order_id: string;
          inspection_item_id: string | null;
          kind: Database['public']['Enums']['line_item_kind'];
          description: string;
          quantity: number;
          unit_price_cents: number;
          unit_cost_cents: number | null;
          taxable: boolean;
          approval: Database['public']['Enums']['approval_state'];
          recommended: boolean;
          sort: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          inspection_item_id?: string | null;
          kind: Database['public']['Enums']['line_item_kind'];
          description: string;
          quantity?: number;
          unit_price_cents: number;
          unit_cost_cents?: number | null;
          taxable?: boolean;
          approval?: Database['public']['Enums']['approval_state'];
          recommended?: boolean;
          sort?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          inspection_item_id?: string | null;
          kind?: Database['public']['Enums']['line_item_kind'];
          description?: string;
          quantity?: number;
          unit_price_cents?: number;
          unit_cost_cents?: number | null;
          taxable?: boolean;
          approval?: Database['public']['Enums']['approval_state'];
          recommended?: boolean;
          sort?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'line_items_inspection_item_id_fkey';
            columns: ['inspection_item_id'];
            isOneToOne: false;
            referencedRelation: 'inspection_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'line_items_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      media: {
        Row: {
          id: string;
          work_order_id: string | null;
          inspection_item_id: string | null;
          vehicle_id: string | null;
          bucket: string;
          path: string;
          kind: Database['public']['Enums']['media_kind'];
          caption: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id?: string | null;
          inspection_item_id?: string | null;
          vehicle_id?: string | null;
          bucket?: string;
          path: string;
          kind?: Database['public']['Enums']['media_kind'];
          caption?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string | null;
          inspection_item_id?: string | null;
          vehicle_id?: string | null;
          bucket?: string;
          path?: string;
          kind?: Database['public']['Enums']['media_kind'];
          caption?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'media_inspection_item_id_fkey';
            columns: ['inspection_item_id'];
            isOneToOne: false;
            referencedRelation: 'inspection_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_uploaded_by_fkey';
            columns: ['uploaded_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_vehicle_id_fkey';
            columns: ['vehicle_id'];
            isOneToOne: false;
            referencedRelation: 'vehicles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'media_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      messages: {
        Row: {
          id: string;
          customer_id: string | null;
          work_order_id: string | null;
          channel: Database['public']['Enums']['message_channel'];
          direction: Database['public']['Enums']['message_direction'];
          to_address: string;
          subject: string | null;
          body: string;
          status: Database['public']['Enums']['message_status'];
          provider_id: string | null;
          error: string | null;
          automation_key: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id?: string | null;
          work_order_id?: string | null;
          channel: Database['public']['Enums']['message_channel'];
          direction?: Database['public']['Enums']['message_direction'];
          to_address: string;
          subject?: string | null;
          body: string;
          status: Database['public']['Enums']['message_status'];
          provider_id?: string | null;
          error?: string | null;
          automation_key?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string | null;
          work_order_id?: string | null;
          channel?: Database['public']['Enums']['message_channel'];
          direction?: Database['public']['Enums']['message_direction'];
          to_address?: string;
          subject?: string | null;
          body?: string;
          status?: Database['public']['Enums']['message_status'];
          provider_id?: string | null;
          error?: string | null;
          automation_key?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'messages_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'messages_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      part_requests: {
        Row: {
          id: string;
          work_order_id: string;
          requested_by: string | null;
          description: string;
          status: Database['public']['Enums']['part_request_status'];
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          requested_by?: string | null;
          description: string;
          status?: Database['public']['Enums']['part_request_status'];
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          requested_by?: string | null;
          description?: string;
          status?: Database['public']['Enums']['part_request_status'];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'part_requests_requested_by_fkey';
            columns: ['requested_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'part_requests_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      payments: {
        Row: {
          id: string;
          invoice_id: string;
          amount_cents: number;
          method: string;
          stripe_payment_intent_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          amount_cents: number;
          method: string;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          amount_cents?: number;
          method?: string;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'payments_invoice_id_fkey';
            columns: ['invoice_id'];
            isOneToOne: false;
            referencedRelation: 'invoices';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          role: Database['public']['Enums']['app_role'];
          full_name: string;
          email: string | null;
          phone: string | null;
          title: string | null;
          avatar_color: string;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          role?: Database['public']['Enums']['app_role'];
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          avatar_color?: string;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: Database['public']['Enums']['app_role'];
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          avatar_color?: string;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [

        ];
      };
      shop_settings: {
        Row: {
          id: number;
          labor_rate_cents: number;
          tax_rate: number;
          parts_taxable: boolean;
          labor_taxable: boolean;
          owner_email: string | null;
          owner_phone: string | null;
          google_review_url: string | null;
          bay_count: number;
          open_hour: number;
          close_hour: number;
          open_days: number[];
          slot_minutes: number;
          updated_at: string;
        };
        Insert: {
          id?: number;
          labor_rate_cents?: number;
          tax_rate?: number;
          parts_taxable?: boolean;
          labor_taxable?: boolean;
          owner_email?: string | null;
          owner_phone?: string | null;
          google_review_url?: string | null;
          bay_count?: number;
          open_hour?: number;
          close_hour?: number;
          open_days?: number[];
          slot_minutes?: number;
          updated_at?: string;
        };
        Update: {
          id?: number;
          labor_rate_cents?: number;
          tax_rate?: number;
          parts_taxable?: boolean;
          labor_taxable?: boolean;
          owner_email?: string | null;
          owner_phone?: string | null;
          google_review_url?: string | null;
          bay_count?: number;
          open_hour?: number;
          close_hour?: number;
          open_days?: number[];
          slot_minutes?: number;
          updated_at?: string;
        };
        Relationships: [

        ];
      };
      time_entries: {
        Row: {
          id: string;
          work_order_id: string;
          tech_id: string;
          started_at: string;
          ended_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          tech_id: string;
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          tech_id?: string;
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'time_entries_tech_id_fkey';
            columns: ['tech_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'time_entries_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      tune_records: {
        Row: {
          id: string;
          vehicle_id: string;
          work_order_id: string | null;
          tuner_platform: string;
          device_serial: string | null;
          ecu: string | null;
          calibrator: string | null;
          file_name: string | null;
          revision: string | null;
          emissions_compliant: boolean | null;
          stock_file_backed_up: boolean;
          notes: string | null;
          flashed_by: string | null;
          flashed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          work_order_id?: string | null;
          tuner_platform: string;
          device_serial?: string | null;
          ecu?: string | null;
          calibrator?: string | null;
          file_name?: string | null;
          revision?: string | null;
          emissions_compliant?: boolean | null;
          stock_file_backed_up?: boolean;
          notes?: string | null;
          flashed_by?: string | null;
          flashed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          work_order_id?: string | null;
          tuner_platform?: string;
          device_serial?: string | null;
          ecu?: string | null;
          calibrator?: string | null;
          file_name?: string | null;
          revision?: string | null;
          emissions_compliant?: boolean | null;
          stock_file_backed_up?: boolean;
          notes?: string | null;
          flashed_by?: string | null;
          flashed_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'tune_records_flashed_by_fkey';
            columns: ['flashed_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'tune_records_vehicle_id_fkey';
            columns: ['vehicle_id'];
            isOneToOne: false;
            referencedRelation: 'vehicles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'tune_records_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      vehicles: {
        Row: {
          id: string;
          customer_id: string;
          vin: string | null;
          year: number | null;
          make: string | null;
          model: string | null;
          platform: string | null;
          generation: string | null;
          engine_code: string | null;
          transmission: string | null;
          mileage: number | null;
          nickname: string | null;
          color: string | null;
          photo_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          vin?: string | null;
          year?: number | null;
          make?: string | null;
          model?: string | null;
          platform?: string | null;
          generation?: string | null;
          engine_code?: string | null;
          transmission?: string | null;
          mileage?: number | null;
          nickname?: string | null;
          color?: string | null;
          photo_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          vin?: string | null;
          year?: number | null;
          make?: string | null;
          model?: string | null;
          platform?: string | null;
          generation?: string | null;
          engine_code?: string | null;
          transmission?: string | null;
          mileage?: number | null;
          nickname?: string | null;
          color?: string | null;
          photo_path?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'vehicles_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          },
        ];
      };
      work_order_events: {
        Row: {
          id: string;
          work_order_id: string;
          from_status: Database['public']['Enums']['work_order_status'] | null;
          to_status: Database['public']['Enums']['work_order_status'];
          actor_id: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          from_status?: Database['public']['Enums']['work_order_status'] | null;
          to_status: Database['public']['Enums']['work_order_status'];
          actor_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          from_status?: Database['public']['Enums']['work_order_status'] | null;
          to_status?: Database['public']['Enums']['work_order_status'];
          actor_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'work_order_events_actor_id_fkey';
            columns: ['actor_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'work_order_events_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      work_order_notes: {
        Row: {
          id: string;
          work_order_id: string;
          author_id: string | null;
          body: string;
          internal: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          author_id?: string | null;
          body: string;
          internal?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          author_id?: string | null;
          body?: string;
          internal?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'work_order_notes_author_id_fkey';
            columns: ['author_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'work_order_notes_work_order_id_fkey';
            columns: ['work_order_id'];
            isOneToOne: false;
            referencedRelation: 'work_orders';
            referencedColumns: ['id'];
          },
        ];
      };
      work_orders: {
        Row: {
          id: string;
          number: number;
          customer_id: string;
          vehicle_id: string;
          lead_id: string | null;
          status: Database['public']['Enums']['work_order_status'];
          title: string;
          complaint: string | null;
          assigned_tech_id: string | null;
          bay: string | null;
          mileage_in: number | null;
          promised_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          review_requested_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number?: number;
          customer_id: string;
          vehicle_id: string;
          lead_id?: string | null;
          status?: Database['public']['Enums']['work_order_status'];
          title: string;
          complaint?: string | null;
          assigned_tech_id?: string | null;
          bay?: string | null;
          mileage_in?: number | null;
          promised_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          review_requested_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: number;
          customer_id?: string;
          vehicle_id?: string;
          lead_id?: string | null;
          status?: Database['public']['Enums']['work_order_status'];
          title?: string;
          complaint?: string | null;
          assigned_tech_id?: string | null;
          bay?: string | null;
          mileage_in?: number | null;
          promised_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          review_requested_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'work_orders_assigned_tech_id_fkey';
            columns: ['assigned_tech_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'work_orders_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'work_orders_lead_id_fkey';
            columns: ['lead_id'];
            isOneToOne: false;
            referencedRelation: 'leads';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'work_orders_vehicle_id_fkey';
            columns: ['vehicle_id'];
            isOneToOne: false;
            referencedRelation: 'vehicles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      app_role: 'admin' | 'employee' | 'client';
      appointment_status: 'scheduled' | 'confirmed' | 'checked_in' | 'completed' | 'cancelled' | 'no_show';
      approval_state: 'pending' | 'approved' | 'declined';
      automation_run_status: 'scheduled' | 'sent' | 'skipped' | 'failed' | 'cancelled';
      inspection_rating: 'green' | 'yellow' | 'red' | 'na';
      inspection_status: 'draft' | 'sent';
      invoice_status: 'open' | 'paid' | 'void';
      lead_status: 'new' | 'contacted' | 'booked' | 'won' | 'lost';
      line_item_kind: 'labor' | 'part' | 'fee';
      media_kind: 'photo' | 'video' | 'document';
      message_channel: 'sms' | 'email';
      message_direction: 'outbound' | 'inbound';
      message_status: 'queued' | 'sent' | 'simulated' | 'failed' | 'skipped';
      part_request_status: 'requested' | 'ordered' | 'received';
      work_order_status: 'estimate' | 'awaiting_approval' | 'approved' | 'in_progress' | 'waiting_parts' | 'quality_check' | 'ready' | 'invoiced' | 'paid' | 'cancelled';
    };
    CompositeTypes: Record<string, never>;
  };
}

type PublicTables = Database['public']['Tables'];
export type Tables<T extends keyof PublicTables> = PublicTables[T]['Row'];
export type TablesInsert<T extends keyof PublicTables> = PublicTables[T]['Insert'];
export type TablesUpdate<T extends keyof PublicTables> = PublicTables[T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
