/**
 * Writes BUSINESS_FACTS_NEEDED.md from lib/site-facts.ts.
 *
 * Generated rather than hand-written so the document cannot drift from the
 * code: a fact removed from the registry disappears from the owner's list in
 * the same commit, and a test fails if the list still asks for something
 * BUSINESS already has.
 *
 * Run: node scripts/facts.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const source = readFileSync(path.join(root, 'lib/site-facts.ts'), 'utf8');

// The registry is a plain literal, so it can be read without a TS toolchain.
const entries = [...source.matchAll(/\{\s*\n\s*id: '([^']+)',\s*\n\s*label: '([^']+)',\s*\n\s*severity: '([^']+)',\s*\n\s*blocks:\s*\n?\s*'((?:[^'\\]|\\.)*)',\s*\n\s*where: '((?:[^'\\]|\\.)*)',/g)]
  .map(([, id, label, severity, blocks, where]) => ({
    id,
    label,
    severity,
    blocks: blocks.replace(/\\'/g, "'").replace(/\s+/g, ' ').trim(),
    where: where.replace(/\\'/g, "'"),
  }));

if (!entries.length) {
  console.error('facts: parsed nothing from lib/site-facts.ts — did the shape change?');
  process.exit(1);
}

const HEADINGS = {
  'blocks-launch': ['1. Before this can go live', 'The site cannot launch without these. Nothing here can be guessed — a made-up address or a wrong set of hours on a shop listing is worse than none.'],
  'blocks-feature': ['2. Switches something on', 'Each of these turns on a feature that is already built and waiting. Partial is fine; every line unblocks on its own.'],
  improves: ['3. Makes the site better', 'Not blocking anything. Worth having when you get a minute.'],
};

const lines = [
  '# Business facts still needed',
  '',
  '<!-- Generated by scripts/facts.mjs from lib/site-facts.ts. Do not edit by hand. -->',
  '',
  'Everything below is something only you can answer. Where a fact is missing the',
  'site says less rather than guessing — so nothing here is broken, it is just',
  'quieter than it should be.',
  '',
  'Answer whatever you know. Each line stands on its own.',
  '',
];

for (const [severity, [heading, blurb]] of Object.entries(HEADINGS)) {
  const group = entries.filter((entry) => entry.severity === severity);
  if (!group.length) continue;
  lines.push('---', '', `## ${heading}`, '', blurb, '');
  for (const entry of group) {
    lines.push(`### ${entry.label}`, '', `**Without it:** ${entry.blocks}`, '', `**Where to find it:** ${entry.where}`, '', '```', `${entry.label}:`.padEnd(46, ' ') + '______________________', '```', '');
  }
}

lines.push('---', '', `_${entries.length} outstanding. Regenerate with \`node scripts/facts.mjs\`._`, '');
writeFileSync(path.join(root, 'BUSINESS_FACTS_NEEDED.md'), lines.join('\n'));
console.log(`facts: wrote BUSINESS_FACTS_NEEDED.md — ${entries.length} outstanding`);
