#!/usr/bin/env node
/**
 * Generates lib/db/database.types.ts from the live public schema, in the shape
 * supabase-js expects. Usage: node --env-file=.env.local scripts/gen-types.mjs
 */
import { writeFile } from 'node:fs/promises';
import postgres from 'postgres';

const sql = postgres(process.env.POSTGRES_URL_NON_POOLING, { ssl: 'require', max: 1 });

const SCALARS = {
  uuid: 'string', text: 'string', 'character varying': 'string', integer: 'number', bigint: 'number',
  smallint: 'number', numeric: 'number', boolean: 'boolean', 'timestamp with time zone': 'string',
  date: 'string', jsonb: 'Json', json: 'Json',
};

try {
  const enums = await sql`
    select t.typname as name, array_agg(e.enumlabel order by e.enumsortorder) as labels
    from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' group by t.typname order by t.typname`;
  const enumNames = new Set(enums.map((e) => e.name));

  const columns = await sql`
    select c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable, c.column_default, c.is_identity
    from information_schema.columns c
    join information_schema.tables t on t.table_name = c.table_name and t.table_schema = c.table_schema
    where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
    order by c.table_name, c.ordinal_position`;

  const fks = await sql`
    select con.conname as name, rel.relname as table_name, frel.relname as referenced_table,
      array_agg(att.attname order by k.ord) as columns,
      array_agg(fatt.attname order by k.ord) as referenced_columns,
      exists (
        select 1 from pg_constraint u
        where u.conrelid = con.conrelid and u.contype in ('u', 'p') and u.conkey = con.conkey
      ) as one_to_one
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace n on n.oid = rel.relnamespace
    join pg_class frel on frel.oid = con.confrelid
    join pg_namespace fn on fn.oid = frel.relnamespace
    cross join lateral unnest(con.conkey, con.confkey) with ordinality as k(attnum, fattnum, ord)
    join pg_attribute att on att.attrelid = con.conrelid and att.attnum = k.attnum
    join pg_attribute fatt on fatt.attrelid = con.confrelid and fatt.attnum = k.fattnum
    where con.contype = 'f' and n.nspname = 'public' and fn.nspname = 'public'
    group by con.oid, con.conname, rel.relname, frel.relname, con.conrelid, con.conkey
    order by con.conname`;
  const relationships = (table) =>
    fks
      .filter((fk) => fk.table_name === table)
      .map(
        (fk) => `          {
            foreignKeyName: '${fk.name}';
            columns: [${fk.columns.map((c) => `'${c}'`).join(', ')}];
            isOneToOne: ${fk.one_to_one};
            referencedRelation: '${fk.referenced_table}';
            referencedColumns: [${fk.referenced_columns.map((c) => `'${c}'`).join(', ')}];
          },`,
      )
      .join('\n');

  const tsType = (col) => {
    if (col.data_type === 'ARRAY') {
      const inner = col.udt_name.replace(/^_/, '');
      const base = enumNames.has(inner) ? `Database['public']['Enums']['${inner}']` : inner === 'uuid' || inner === 'text' ? 'string' : 'number';
      return `${base}[]`;
    }
    if (col.data_type === 'USER-DEFINED' && enumNames.has(col.udt_name)) return `Database['public']['Enums']['${col.udt_name}']`;
    return SCALARS[col.data_type] ?? 'unknown';
  };

  const tables = new Map();
  for (const col of columns) {
    if (!tables.has(col.table_name)) tables.set(col.table_name, []);
    tables.get(col.table_name).push(col);
  }

  const block = (cols, mode) =>
    cols
      .map((col) => {
        const nullable = col.is_nullable === 'YES';
        const hasDefault = col.column_default !== null || col.is_identity === 'YES';
        const type = `${tsType(col)}${nullable ? ' | null' : ''}`;
        const optional = mode === 'Update' || (mode === 'Insert' && (nullable || hasDefault));
        return `          ${col.column_name}${optional ? '?' : ''}: ${type};`;
      })
      .join('\n');

  const tableDefs = [...tables.entries()]
    .map(
      ([name, cols]) => `      ${name}: {
        Row: {
${block(cols, 'Row')}
        };
        Insert: {
${block(cols, 'Insert')}
        };
        Update: {
${block(cols, 'Update')}
        };
        Relationships: [
${relationships(name)}
        ];
      };`,
    )
    .join('\n');

  const enumDefs = enums.map((e) => `      ${e.name}: ${e.labels.map((l) => `'${l}'`).join(' | ')};`).join('\n');

  const out = `// Generated by scripts/gen-types.mjs — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
${tableDefs}
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
${enumDefs}
    };
    CompositeTypes: Record<string, never>;
  };
}

type PublicTables = Database['public']['Tables'];
export type Tables<T extends keyof PublicTables> = PublicTables[T]['Row'];
export type TablesInsert<T extends keyof PublicTables> = PublicTables[T]['Insert'];
export type TablesUpdate<T extends keyof PublicTables> = PublicTables[T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
`;
  await writeFile('lib/db/database.types.ts', out);
  console.log(`wrote lib/db/database.types.ts (${tables.size} tables, ${enums.length} enums)`);
} finally {
  await sql.end();
}
