import type { Enums } from '@/lib/db/database.types';

/**
 * Default automations. Seeded into the `automations` table, where the owner
 * can toggle them and edit the wording. `key` is stable; code refers to it.
 *
 * Trigger events:
 *   lead.created · appointment.booked · work_order.status:<status> · inspection.sent
 *   estimate.approved · invoice.created · invoice.paid · daily.summary · service.due
 */
export interface AutomationDefinition {
  key: string;
  name: string;
  description: string;
  triggerEvent: string;
  audience: 'customer' | 'owner' | 'tech';
  channels: Enums<'message_channel'>[];
  anchor: 'event' | 'before_appointment';
  delayMinutes: number;
  sms?: string;
  emailSubject?: string;
  emailBody?: string;
}

const HOUR = 60;
const DAY = 24 * HOUR;

export const AUTOMATIONS: readonly AutomationDefinition[] = [
  // ── Leads ──
  {
    key: 'lead_owner_alert',
    name: 'New lead alert',
    description: 'Tell the owner the moment a service request comes in.',
    triggerEvent: 'lead.created',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "New lead: {{customer_name}} - {{vehicle}} - {{service}}. {{customer_phone}}. Open: {{admin_link}}",
    emailSubject: 'New service request — {{customer_name}} ({{service}})',
    emailBody:
      '{{customer_name}} just requested {{service}}.\n\nTruck: {{vehicle}}\nMileage: {{mileage}}\nPhone: {{customer_phone}}\nEmail: {{customer_email}}\n\n"{{details}}"\n\nOpen the lead: {{admin_link}}',
  },
  {
    key: 'lead_auto_reply',
    name: 'Lead auto-reply',
    description: 'Confirm the request instantly so the customer doesn’t call the next shop.',
    triggerEvent: 'lead.created',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Hey {{first_name}}, Lucky Diesel here. Got your {{service}} request for the {{vehicle}}. We'll reach out shortly. Reply STOP to opt out.",
    emailSubject: 'We got your request, {{first_name}}',
    emailBody:
      'Hey {{first_name}},\n\nThanks for reaching out about {{service}} for your {{vehicle}}. We’ll get back to you shortly with next steps.\n\nNeed us sooner? Call or text {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'lead_follow_up_1d',
    name: 'Lead follow-up (day 1)',
    description: 'If a lead hasn’t booked after a day, check in.',
    triggerEvent: 'lead.created',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: DAY,
    sms: "Hi {{first_name}}, still want to get the {{vehicle}} in for {{service}}? Book a time here: {{booking_link}}",
  },
  {
    key: 'lead_follow_up_3d',
    name: 'Lead follow-up (day 3)',
    description: 'Last friendly nudge before the lead goes cold.',
    triggerEvent: 'lead.created',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 3 * DAY,
    emailSubject: 'Still thinking about your {{vehicle}}?',
    emailBody:
      'Hey {{first_name}},\n\nJust following up on your {{service}} request. If you have questions about parts, tuning or pricing, reply to this email or call {{shop_phone}}.\n\nBook a time: {{booking_link}}\n\n— Lucky Diesel',
  },
  // ── Appointments ──
  {
    key: 'appointment_confirmation',
    name: 'Booking confirmation',
    description: 'Confirm the date and time as soon as it’s booked.',
    triggerEvent: 'appointment.booked',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "You're booked, {{first_name}}: {{service}} on {{appointment_time}}. See details in your portal: {{portal_link}}",
    emailSubject: 'Booked: {{service}} on {{appointment_time}}',
    emailBody:
      'Hey {{first_name}},\n\nYou’re on the schedule for {{service}} on {{appointment_time}}.\n\nYour portal: {{portal_link}}\n\nNeed to change it? Call or text {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'booking_owner_alert',
    name: 'New booking alert',
    description: 'Tell the owner when someone books online.',
    triggerEvent: 'appointment.booked',
    audience: 'owner',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "New booking: {{customer_name}} - {{vehicle}} - {{service}} - {{appointment_time}}. {{admin_link}}",
  },
  {
    key: 'appointment_reminder_24h',
    name: 'Appointment reminder (24h)',
    description: 'Cut no-shows with a reminder the day before.',
    triggerEvent: 'appointment.booked',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'before_appointment',
    delayMinutes: DAY,
    sms: "Reminder: {{vehicle}} is booked at Lucky Diesel tomorrow, {{appointment_time}}. Reply C to confirm or call {{shop_phone}} to reschedule.",
  },
  {
    key: 'appointment_reminder_2h',
    name: 'Appointment reminder (2h)',
    description: 'A final heads-up on the day.',
    triggerEvent: 'appointment.booked',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'before_appointment',
    delayMinutes: 2 * HOUR,
    sms: "See you soon, {{first_name}}. Your {{service}} appointment is at {{appointment_time}}.",
  },
  // ── Work orders ──
  {
    key: 'job_checked_in',
    name: 'Truck checked in',
    description: 'Let the customer know work has started and where to follow along.',
    triggerEvent: 'work_order.status:in_progress',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Your {{vehicle}} is in the bay, {{first_name}}. Follow progress live: {{portal_link}}",
  },
  {
    key: 'inspection_ready',
    name: 'Inspection & estimate ready',
    description: 'Send the photo inspection and estimate for approval.',
    triggerEvent: 'inspection.sent',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "{{first_name}}, your inspection for the {{vehicle}} is ready: {{recommended_count}} items with photos, {{estimate_total}}. Review & approve: {{approval_link}}",
    emailSubject: 'Your {{vehicle}} inspection is ready to review',
    emailBody:
      'Hey {{first_name}},\n\nWe finished inspecting your {{vehicle}}. There are {{recommended_count}} recommended items totaling {{estimate_total}}, each with photos and notes.\n\nApprove or decline each item here: {{approval_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'estimate_nudge',
    name: 'Estimate approval nudge',
    description: 'If an estimate isn’t answered in 4 hours, send a gentle reminder.',
    triggerEvent: 'inspection.sent',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 4 * HOUR,
    sms: "Hi {{first_name}}, we're holding your {{vehicle}} until you review the estimate. Approve here: {{approval_link}} or call {{shop_phone}}.",
  },
  {
    key: 'estimate_decision_alert',
    name: 'Approval alert to shop',
    description: 'Tell the tech and owner the moment the customer approves.',
    triggerEvent: 'estimate.approved',
    audience: 'tech',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "WO #{{work_order}} approved by {{customer_name}}: {{approved_total}}. Good to go on the {{vehicle}}.",
  },
  {
    key: 'waiting_parts',
    name: 'Waiting on parts',
    description: 'Keep the customer in the loop when parts hold up a job.',
    triggerEvent: 'work_order.status:waiting_parts',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Update on your {{vehicle}}: we're waiting on parts. We'll text you as soon as they land. {{portal_link}}",
  },
  {
    key: 'job_ready',
    name: 'Truck ready for pickup',
    description: 'Pickup notice with the invoice and pay link.',
    triggerEvent: 'invoice.created',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Your {{vehicle}} is ready, {{first_name}}! Invoice {{invoice_total}}. Pay online to skip the counter: {{pay_link}}",
    emailSubject: 'Your {{vehicle}} is ready — invoice #{{invoice_number}}',
    emailBody:
      'Hey {{first_name}},\n\nYour {{vehicle}} is done and ready for pickup.\n\nInvoice #{{invoice_number}}: {{invoice_total}}\nPay online: {{pay_link}}\n\nWork details, photos and your truck’s history are in your portal: {{portal_link}}\n\n— Lucky Diesel',
  },
  // ── After the job ──
  {
    key: 'payment_receipt',
    name: 'Payment receipt',
    description: 'Receipt and thanks as soon as an invoice is paid.',
    triggerEvent: 'invoice.paid',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Receipt for invoice #{{invoice_number}}',
    emailBody:
      'Thanks, {{first_name}}.\n\nWe received your payment of {{invoice_total}} for invoice #{{invoice_number}} ({{vehicle}}).\n\nYour full service record is in your portal: {{portal_link}}\n\nHow did we do? Reviews help other diesel owners find us: {{review_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'review_request',
    name: 'Google review request',
    description: 'Asks every customer for a review the day after pickup. No filtering, per Google policy.',
    triggerEvent: 'invoice.paid',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: DAY,
    sms: "Thanks for trusting us with the {{vehicle}}, {{first_name}}. Mind sharing how it went? {{review_link}}",
  },
  {
    key: 'review_reminder',
    name: 'Review reminder',
    description: 'One reminder, three days later, only if they haven’t been asked again.',
    triggerEvent: 'invoice.paid',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 4 * DAY,
    emailSubject: 'How’s the {{vehicle}} running?',
    emailBody:
      'Hey {{first_name}},\n\nHope the truck is running strong. If you have a minute, a Google review helps other diesel owners find us: {{review_link}}\n\nAnything not right? Reply here and it comes straight to the owner.\n\n— Lucky Diesel',
  },
  {
    key: 'service_due',
    name: 'Service due reminder',
    description: 'Brings customers back when maintenance or a tune check is due.',
    triggerEvent: 'service.due',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Hey {{first_name}}, the {{vehicle}} is due for {{due_service}}. Grab a time: {{booking_link}}",
  },
  {
    key: 'declined_work_follow_up',
    name: 'Declined work follow-up',
    description: '30 days after an item is declined, remind the customer it’s still recommended.',
    triggerEvent: 'estimate.approved',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 30 * DAY,
    emailSubject: 'Still on the list for your {{vehicle}}',
    emailBody:
      'Hey {{first_name}},\n\nLast visit we recommended: {{declined_items}}. Want to get it taken care of? Book here: {{booking_link}}\n\n— Lucky Diesel',
  },
  // ── Owner ──
  {
    key: 'daily_summary',
    name: 'Owner daily summary',
    description: '7am email: today’s schedule, new leads, open estimates and unpaid invoices.',
    triggerEvent: 'daily.summary',
    audience: 'owner',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Lucky Diesel today: {{appointments_today}} appointments, {{new_leads}} new leads',
    emailBody:
      'Good morning.\n\nToday: {{appointments_today}} appointments\nIn the shop: {{open_jobs}} open jobs\nNew leads (24h): {{new_leads}}\nWaiting on approval: {{awaiting_approval}}\nUnpaid invoices: {{unpaid_total}}\nRevenue this week: {{week_revenue}}\n\nDashboard: {{admin_link}}',
  },
  // ── Marketing lifecycle (lib/marketing/core/lifecycle.ts emits these daily) ──
  // Keys starting with `mkt_` are promotional: sendMessage applies marketing
  // consent, suppressions, weekly caps and 8am–9pm quiet hours to them.
  {
    key: 'mkt_win_back_6m',
    name: 'Win-back (6 months)',
    description: 'Six months since the last paid visit and nothing booked: invite them back.',
    triggerEvent: 'marketing.win_back_6m',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel here, {{first_name}}. It's been about 6 months since we saw {{vehicle}}. Due for {{due_service}}? Book: {{booking_link}} Reply STOP to opt out.",
  },
  {
    key: 'mkt_win_back_12m',
    name: 'Win-back (12 months)',
    description: 'A year without a visit: a personal note from the shop.',
    triggerEvent: 'marketing.win_back_12m',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Been a while, {{first_name}}',
    emailBody:
      'Hey {{first_name}},\n\nIt’s been about a year since {{vehicle}} was in the shop. A yearly once-over catches small leaks, worn filters and fuel system issues before they strand you.\n\nGrab a time that works: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_tune_follow_up',
    name: 'Post-tune check-in',
    description: 'Three days after a tune: any codes, regens or drivability questions?',
    triggerEvent: 'marketing.tune_follow_up',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel checking in, {{first_name}}. How is {{vehicle}} running since the tune? Any codes or questions, reply here. We offer {{due_service}} anytime.",
  },
  {
    key: 'mkt_dyno_recheck',
    name: 'Dyno re-check offer',
    description: 'About a month after a tune, offer a re-check pull and datalog review.',
    triggerEvent: 'marketing.dyno_recheck',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: {{first_name}}, it's been a month on the tune. Want {{due_service}} to confirm {{vehicle}} is dialed in? {{booking_link}} Reply STOP to opt out.",
  },
  {
    key: 'mkt_seasonal_towing',
    name: 'Towing season prep',
    description: 'Spring (Mar–mid Apr): pre-season towing inspection for boat and camper season.',
    triggerEvent: 'marketing.seasonal.towing_season',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: boat and camper season is close, {{first_name}}. Book {{due_service}} for {{vehicle}}: trans, cooling, brakes. {{booking_link}} Reply STOP to opt out.",
    emailSubject: 'Ready to tow this season?',
    emailBody:
      'Hey {{first_name}},\n\nTowing season is almost here. Before the first trip to the ramp, we’ll check transmission fluid and temps, cooling system, brakes and trailer wiring on {{vehicle}}.\n\nBook {{due_service}}: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_hurricane',
    name: 'Hurricane season readiness',
    description: 'Late May: evacuation-ready truck check. Service reminder tone, no crisis selling.',
    triggerEvent: 'marketing.seasonal.hurricane_prep',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Is your truck evacuation-ready?',
    emailBody:
      'Hey {{first_name}},\n\nHurricane season starts June 1. If you ever need to leave in a hurry or tow family and gear inland, {{vehicle}} should be ready: fuel filters, batteries, cooling system and tires.\n\nBook {{due_service}}: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_winter',
    name: 'Winter diesel prep',
    description: 'Mid Oct–Nov: cold starts, batteries, glow plugs/grid heater and anti-gel before trips north.',
    triggerEvent: 'marketing.seasonal.winter_diesel',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Heading north or hunting inland this winter?',
    emailBody:
      'Hey {{first_name}},\n\nCharleston rarely gels, but a cold morning up the road can. Before winter trips we check batteries, glow plugs or grid heater, fuel filters and add anti-gel treatment.\n\nBook {{due_service}} for {{vehicle}}: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_birthday',
    name: 'Birthday note',
    description: 'Only for customers who volunteered a birthday.',
    triggerEvent: 'marketing.birthday',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Happy birthday, {{first_name}}',
    emailBody: 'Hey {{first_name}},\n\nHappy birthday from everyone at Lucky Diesel. Thanks for trusting us with {{vehicle}}.\n\nNext time you’re in, mention your birthday month and the coffee’s on us.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_customer_anniversary',
    name: 'Customer anniversary',
    description: 'Yearly thank-you on the date of the first paid visit.',
    triggerEvent: 'marketing.customer_anniversary',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Thanks for {{due_service}}',
    emailBody: 'Hey {{first_name}},\n\nToday marks {{due_service}}. We appreciate you trusting us with {{vehicle}}.\n\nIf it’s been a while, book a check-up: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_build_plan_follow_up',
    name: 'Build plan follow-up',
    description: 'Planner quote requests with no booking after 5 days.',
    triggerEvent: 'marketing.build_plan_abandoned',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Still planning the {{vehicle}} build?',
    emailBody:
      'Hey {{first_name}},\n\nYou put together a build plan with us last week. Happy to walk through parts, install time and pricing, or break it into stages that fit the budget.\n\nReply to this email, call {{shop_phone}}, or book a consult: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_store_checkout_follow_up',
    name: 'Parts checkout follow-up',
    description: 'Shopify has no abandoned-checkout webhook, so this uses our store checkout-click event (consented contacts only).',
    triggerEvent: 'marketing.store_checkout_click',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Want us to install those parts?',
    emailBody:
      'Hey {{first_name}},\n\nLooks like you were checking out parts on our store. If you have fit questions, or want us to install them on {{vehicle}}, reply here or book an install: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_abandoned_quote',
    name: 'Unfinished quote reminder',
    description: 'One email 1h after a quote form was left unfinished (only if they ticked “remind me”).',
    triggerEvent: 'marketing.abandoned_quote',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Finish your service request?',
    emailBody:
      'Hey {{first_name}},\n\nYou started a request for {{due_service}} but didn’t get to send it. No problem. Pick a time here: {{booking_link}}\n\nOr call {{shop_phone}} and we’ll take it from there.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_referral_thank_you',
    name: 'Referral thank-you',
    description: 'Thanks the referrer as soon as a friend uses their code.',
    triggerEvent: 'marketing.referral_created',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: thanks for sending a friend our way, {{first_name}}! You'll get {{due_service}} once their first job is done. Reply STOP to opt out.",
  },
  {
    key: 'mkt_referral_reward',
    name: 'Referral reward earned',
    description: 'Tells the referrer their reward is ready after the friend’s first paid job.',
    triggerEvent: 'marketing.referral_rewarded',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: your referral paid off, {{first_name}}. {{due_service}} is on your account for your next visit. Reply STOP to opt out.",
    emailSubject: 'Your referral reward is ready',
    emailBody: 'Hey {{first_name}},\n\nYour friend’s first job is done, so {{due_service}} is now on your account. It applies automatically at your next visit.\n\nThanks for spreading the word.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_referral_ask',
    name: 'Referral ask',
    description: 'A few days after a paid job or a 9–10 survey score. Never tied to reviews. Max twice a year.',
    triggerEvent: 'marketing.referral_ask',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: thanks for trusting us with {{vehicle}}, {{first_name}}. Know a diesel owner? Share your link and you both save: {{due_service}} Reply STOP to opt out.",
  },
  {
    key: 'mkt_tier_upgraded',
    name: 'Loyalty tier upgrade',
    description: 'Tells a customer they reached a new tier and what the perk is.',
    triggerEvent: 'marketing.tier_upgraded',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'You made {{due_service}}',
    emailBody: 'Hey {{first_name}},\n\nThanks for your loyalty. You just reached {{due_service}}. Perks apply at the counter on your next visit.\n\nBook anytime: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_offer_expiring',
    name: 'Offer ending soon',
    description: '48 hours before an offer ends, for people who got it and haven’t used it.',
    triggerEvent: 'marketing.offer_expiring',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: heads up, {{first_name}}. {{due_service}}. Book: {{booking_link}} Reply STOP to opt out.",
  },
  {
    key: 'review_detractor_follow_up',
    name: 'Unhappy feedback follow-up',
    description: 'Private service recovery after a low survey score (the owner alert is content_nps_low_score_alert). The Google review link still goes to everyone; nothing is gated or suppressed.',
    triggerEvent: 'marketing.review_detractor',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "{{first_name}}, thank you for the honest feedback. The owner of Lucky Diesel will call you personally to make it right. You can also reach us at {{shop_phone}}.",
  },
  {
    key: 'mkt_fleet_pm_reminder',
    name: 'Fleet PM reminder',
    description: 'Weekly digest to the fleet manager when units are due by miles or days.',
    triggerEvent: 'marketing.fleet_pm_due',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Fleet maintenance due: {{due_service}}',
    emailBody:
      'Hi {{first_name}},\n\nThese units are due for preventive maintenance: {{due_service}}.\n\nReply with the days that work and we’ll batch them to keep trucks on the road, or book here: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_dyno_day_invite',
    name: 'Dyno day invite',
    description: 'Invites tuned-truck owners 1–3 weeks before a dyno day.',
    triggerEvent: 'marketing.dyno_day_invite',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: {{first_name}}, you're invited to {{due_service}}. Bring {{vehicle}} and see what it makes. Details: {{booking_link}} Reply STOP to opt out.",
    emailSubject: 'You’re invited: {{due_service}}',
    emailBody:
      'Hey {{first_name}},\n\nWe’re hosting {{due_service}} at the shop. Bring {{vehicle}}, make a pull and hang out with other diesel owners. Only street-legal, emissions-compliant trucks on the dyno.\n\nSave a spot: {{booking_link}}\n\n— Lucky Diesel',
  },
  // ── Retention, seasonal and reputation (B4: lib/marketing/core/lifecycle-retention.ts, recalls.ts, local-triggers.ts) ──
  {
    key: 'mkt_welcome_1',
    name: 'Welcome (day 0)',
    description: 'First paid visit: thanks and what the portal holds.',
    triggerEvent: 'marketing.welcome_1',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Welcome to Lucky Diesel, {{first_name}}',
    emailBody: 'Hey {{first_name}},\n\nThanks for trusting us with {{vehicle}}. Photos, invoices and your truck’s history live in your portal: {{portal_link}}\n\nQuestions? Call or text {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_welcome_2',
    name: 'Welcome (day 7)',
    description: 'A week later: how is it running, and who to text.',
    triggerEvent: 'marketing.welcome_2',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'How’s {{vehicle}} running?',
    emailBody: 'Hey {{first_name}},\n\nIt’s been a week. If anything feels off, text {{shop_phone}} and a tech will get back to you.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_welcome_3',
    name: 'Welcome (day 30)',
    description: 'A month in: maintenance rhythm and booking link.',
    triggerEvent: 'marketing.welcome_3',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Keeping {{vehicle}} on schedule',
    emailBody: 'Hey {{first_name}},\n\nWe’ll remind you when service is due based on your mileage. Want to lock in a time now? {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_install_follow_up',
    name: 'Post-install check-in',
    description: 'Timed by job type: injectors 7d, turbo 14d, trans 21d, head studs 30d.',
    triggerEvent: 'marketing.install_follow_up',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: checking in on {{due_service}}, {{first_name}}. Anything feel off on {{vehicle}}? Reply here. Reply STOP to opt out.",
  },
  {
    key: 'mkt_mileage_ask',
    name: 'Mileage check-in',
    description: 'A week before predicted service: asks for the odometer.',
    triggerEvent: 'marketing.mileage_ask',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: {{vehicle}} may be close to {{due_service}}. Reply with your mileage or update it here: {{portal_link}} Reply STOP to opt out.",
  },
  {
    key: 'mkt_lost_lead_60',
    name: 'Lost lead (60 days)',
    description: 'Leads marked lost get one friendly note two months later.',
    triggerEvent: 'marketing.lost_lead_60',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Still need help with your truck?',
    emailBody: 'Hey {{first_name}},\n\nYou reached out a while back. If the truck still needs attention, we have openings: {{booking_link}}\n\nNo pressure. Reply anytime.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_lost_lead_120',
    name: 'Lost lead (120 days)',
    description: 'Last check-in four months after a lost lead.',
    triggerEvent: 'marketing.lost_lead_120',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'One last check-in from Lucky Diesel',
    emailBody: 'Hey {{first_name}},\n\nJust checking in one last time. When the truck needs service, diagnostics or parts, we’re here: {{booking_link}} or {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_tune_revision',
    name: 'Tune revision available',
    description: 'Sent when you log a new calibrator revision for trucks on an older one.',
    triggerEvent: 'marketing.tune_revision',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Tune update available for {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\n{{due_service}} is out for your emissions-compliant tune. We can load it and check a datalog in one visit.\n\nBook: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_warranty_expiring',
    name: 'Parts warranty ending',
    description: '30 days before a part’s warranty ends.',
    triggerEvent: 'marketing.warranty_expiring',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Warranty ending soon on {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nWe recommend {{due_service}}. If anything’s wrong, it’s still covered.\n\nBook: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_build_anniversary',
    name: 'Build anniversary',
    description: 'Yearly on the build’s first install date. Asks for a photo.',
    triggerEvent: 'marketing.build_anniversary',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Happy build anniversary, {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nToday marks {{due_service}}. Send us a current photo of the truck, we love seeing them out working.\n\nDue for a once-over? {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_known_issue',
    name: 'Platform tips',
    description: 'Once per truck: what to watch on this engine.',
    triggerEvent: 'marketing.known_issue',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'What to watch on {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nOwners of trucks like yours should know about {{due_service}}. Catching it early costs far less than a failure.\n\nWant us to take a look? {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_next_stage',
    name: 'Next build stage',
    description: '60 days after a tune, turbo or injector job.',
    triggerEvent: 'marketing.next_stage',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Next step for {{vehicle}}?',
    emailBody: 'Hey {{first_name}},\n\nIf you’re planning the next stage, owners usually look at {{due_service}}. We only build street-legal, emissions-compliant setups.\n\nPlan it with us: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_parts_cross_sell',
    name: 'Parts for next service',
    description: '14 days after maintenance: filters and fluids for their platform.',
    triggerEvent: 'marketing.parts_cross_sell',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Stock up for {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nKeep {{due_service}} on the shelf. Parts that fit your truck: {{store_link}}\n\nOr let us handle it: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_portal_nudge',
    name: 'Portal activation nudge',
    description: 'Days 2 and 7 after a first job, if the portal was never opened.',
    triggerEvent: 'marketing.portal_nudge',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Your truck’s records are ready',
    emailBody: 'Hey {{first_name}},\n\nInspection photos, invoices and {{due_service}} are in your portal: {{portal_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_nps_promoter_referral',
    name: 'Promoter referral ask',
    description: 'Two days after a 9–10 survey score: share a referral link. Not tied to reviews.',
    triggerEvent: 'marketing.nps_promoter',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 2 * DAY,
    sms: "Lucky Diesel: thanks for the great score, {{first_name}}! Know a diesel owner who needs a shop? Share your link: {{referral_link}} Reply STOP to opt out.",
  },
  {
    key: 'mkt_recall_notice',
    name: 'Open recall notice',
    description: 'Weekly NHTSA check by year, make and model.',
    triggerEvent: 'marketing.recall_open',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Recall notice for {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nNHTSA lists an open recall that may apply to {{vehicle}}: {{due_service}}.\n\nRecall repairs are done free at a franchised dealer. Check your VIN at nhtsa.gov/recalls. Questions? Call {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_summer_heat',
    name: 'Summer heat check',
    description: 'Mid Jun–Jul: cooling system check before towing in the heat.',
    triggerEvent: 'marketing.seasonal.summer_heat',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Beat the heat: cooling check for {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nLowcountry heat plus a trailer is hard on coolant, fans and trans temps. Book {{due_service}}: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_hunting',
    name: 'Hunting season prep',
    description: 'Aug 15–Sep: for customers tagged hunting, tows or offroad.',
    triggerEvent: 'marketing.seasonal.hunting_season',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Ready for opening day?',
    emailBody: 'Hey {{first_name}},\n\nBefore the long drives to the lease, get {{due_service}}: tires, batteries, fuel filters and 4x4.\n\nBook: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_tax_refund',
    name: 'Tax refund build season',
    description: 'Feb–mid Mar: plan a build with the refund.',
    triggerEvent: 'marketing.seasonal.tax_refund',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Plan your next stage for {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nRefund season is a good time to plan upgrades in stages that fit the budget. Try the build planner: {{planner_link}}\n\nOr book a consult: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_holiday_parts',
    name: 'Holiday parts',
    description: 'Late Nov–Dec 20: gift ideas and parts for diesel owners.',
    triggerEvent: 'marketing.seasonal.holiday_parts',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Gift ideas for diesel owners',
    emailBody: 'Hey {{first_name}},\n\nShopping for a truck person (or yourself)? Browse {{due_service}}: {{store_link}}\n\nWe can install anything you pick up: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_weather_freeze',
    name: 'Freeze warning',
    description: 'NWS freeze alert for Charleston County: cold-start tips.',
    triggerEvent: 'marketing.weather.freeze',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Freeze tonight: protect {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nThe weather service issued {{due_service}}. Plug in the block heater if you have one, keep the tank full and let it idle a few minutes before working it.\n\nNo-start in the morning? Call {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_weather_storm',
    name: 'Storm watch',
    description: 'NWS hurricane or tropical storm watch: readiness checklist, no crisis selling.',
    triggerEvent: 'marketing.weather.storm',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Storm watch: truck checklist',
    emailBody: 'Hey {{first_name}},\n\nThe weather service issued {{due_service}}. Fill the tank, check tires and keep the truck parked on high ground. Stay safe.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_open_bay',
    name: 'Open bay offer',
    description: 'When the next 2–3 days have lots of open slots, texts recent customers.',
    triggerEvent: 'marketing.open_bay',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: we have open bays {{due_service}}, {{first_name}}. Need service on {{vehicle}}? Grab a slot: {{booking_link}} Reply STOP to opt out.",
  },
  {
    key: 'declined_work_safety_3d',
    name: 'Declined safety item',
    description: '3 days after a declined brake, steering or tire item.',
    triggerEvent: 'estimate.approved',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 3 * DAY,
    sms: "Hi {{first_name}}, Lucky Diesel here. We flagged a safety item on {{vehicle}}: {{declined_items}}. Happy to get it done soon: {{booking_link}}",
  },
  {
    key: 'declined_work_follow_up_7d',
    name: 'Declined work (7 days)',
    description: 'A week after items are declined, one reminder.',
    triggerEvent: 'estimate.approved',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 7 * DAY,
    sms: "Hi {{first_name}}, still want us to handle {{declined_items}} on {{vehicle}}? Book: {{booking_link}}",
  },
  {
    key: 'declined_work_follow_up_90d',
    name: 'Declined work (90 days)',
    description: 'A final reminder 90 days later.',
    triggerEvent: 'estimate.approved',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 90 * DAY,
    emailSubject: 'Still recommended for {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nA few months ago we recommended: {{declined_items}}. Worth a look before it gets worse: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'content_video_testimonial_request',
    name: 'Video testimonial request',
    description: 'Sent when you ask a customer for a short video. No rewards offered.',
    triggerEvent: 'marketing.video_testimonial_request',
    audience: 'customer',
    channels: ['email', 'sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: {{first_name}}, would you record a short video about your truck? Upload here (you choose what we can share): {{upload_link}} Reply STOP to opt out.',
    emailSubject: 'Would you share a quick video, {{first_name}}?',
    emailBody: 'Hey {{first_name}},\n\nWould you record a 30-second video about your truck and your experience? Say what you like, good or bad.\n\nUpload it here and choose how we can use it: {{upload_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'missed_call_text_back',
    name: 'Missed-call text-back',
    description: 'Texts a caller within a minute when a call goes unanswered. Sent by the Twilio voice webhook, not by emit.',
    triggerEvent: 'call.missed',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Sorry we missed your call, this is Lucky Diesel. We're under a truck right now. How can we help? Reply here or book online: {{booking_link}}",
  },
  // ── Marketing content (part B): sent by lib/marketing/content, not by emit ──
  {
    key: 'content_review_negative_alert',
    name: 'Negative review alert',
    description: 'Tells the owner right away when a 1–3 star review comes in, with a drafted reply waiting for approval.',
    triggerEvent: 'marketing.review_negative',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: new {{rating}}-star review from {{author}} on {{source}}. A reply draft is waiting: {{admin_link}}',
    emailSubject: '{{rating}}-star review from {{author}}',
    emailBody:
      '{{author}} left a {{rating}}-star review on {{source}}:\n\n"{{review_text}}"\n\nA reply draft is waiting for your approval (nothing posts without you): {{admin_link}}',
  },
  {
    key: 'content_nps_survey',
    name: 'Post-job survey (NPS)',
    description: '3 days after a paid job: a 0–10 survey plus the Google review link for everyone. Scores never decide who gets the link.',
    triggerEvent: 'marketing.nps_request',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 3 * DAY,
    sms: 'Lucky Diesel: how likely are you to recommend us, 0–10? {{nps_link}} Reviews help too: {{review_link}} Reply STOP to opt out.',
    emailSubject: 'How did we do on the {{vehicle}}?',
    emailBody:
      'Hey {{first_name}},\n\nOne quick question: how likely are you to recommend Lucky Diesel to a friend, 0–10?\n{{nps_link}}\n\nIf you have a minute, a Google review helps other diesel owners find us: {{review_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'content_nps_low_score_alert',
    name: 'Low survey score alert',
    description: 'Tells the owner when a survey score is 0–6 so they can call the customer.',
    triggerEvent: 'marketing.nps_low_score',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: {{customer_name}} scored us {{score}}/10. "{{comment}}" Call them: {{customer_phone}}',
    emailSubject: 'Low survey score from {{customer_name}} ({{score}}/10)',
    emailBody: '{{customer_name}} scored us {{score}}/10.\n\nComment: "{{comment}}"\n\nPhone: {{customer_phone}}\nThey still received the review link, as every customer does.',
  },
  {
    key: 'content_drafts_ready',
    name: 'Marketing drafts ready',
    description: 'Emails the owner when new ads, posts or replies are waiting for approval.',
    triggerEvent: 'marketing.drafts_ready',
    audience: 'owner',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: '{{count}} marketing drafts waiting for you',
    emailBody: 'New drafts are ready: {{summary}}\n\nNothing publishes until you approve it: {{admin_link}}',
  },
  {
    key: 'content_campaign_paused',
    name: 'Ad campaign auto-paused',
    description: 'Tells the owner when a budget guard pauses an ad campaign.',
    triggerEvent: 'marketing.campaign_paused',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: ad campaign "{{campaign}}" was paused ({{reason}}). {{admin_link}}',
    emailSubject: 'Paused: {{campaign}}',
    emailBody: 'The budget guard paused "{{campaign}}" because {{reason}}.\n\nReview it before turning it back on: {{admin_link}}',
  },
  {
    key: 'content_ad_alert',
    name: 'Ad spend alert',
    description: 'Tells the owner when a live campaign spends with no leads, cost per lead jumps, or an ad goes stale.',
    triggerEvent: 'marketing.ad_alert',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel ads: "{{campaign}}": {{alert}}. {{admin_link}}',
    emailSubject: 'Ad alert: {{campaign}}',
    emailBody: '"{{campaign}}": {{alert}}.\n\nNothing was changed. Review it: {{admin_link}}',
  },
  {
    key: 'content_lead_magnet_delivery',
    name: 'Lead magnet delivery',
    description: 'Emails the requested checklist straight away.',
    triggerEvent: 'marketing.lead_magnet',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: '{{magnet_title}}',
    emailBody: 'Hey {{first_name}},\n\nHere’s your {{magnet_title}}.\n\n{{magnet_body}}\n\nWant us to handle it? Book a bay: {{booking_link}} or call {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'content_weekly_digest',
    name: 'Weekly marketing digest',
    description: 'Monday email to the owner: last week’s leads, bookings, revenue and spend. Also kept in Marketing → Reports.',
    triggerEvent: 'marketing.weekly_digest',
    audience: 'owner',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Weekly marketing: {{headline}}',
    emailBody: '{{digest_text}}\n\nFull reports: {{admin_link}}',
  },
  {
    key: 'content_anomaly_alert',
    name: 'Marketing anomaly alert',
    description: 'Tells the owner when leads, bookings, spend or cost per lead swing hard against the last 4 weeks.',
    triggerEvent: 'marketing.anomaly',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel marketing: {{alert}} {{admin_link}}',
    emailSubject: 'Marketing alert',
    emailBody: '{{alert}}\n\nCheck it here: {{admin_link}}',
  },
  // ── Events, fleet & store (sent by lib/marketing/community/sweep.ts, daily) ──
  {
    key: 'event_reminder',
    name: 'Event reminder',
    description: 'Reminds people who signed up, a week out and the day before.',
    triggerEvent: 'community.event_reminder',
    audience: 'customer',
    channels: ['email', 'sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: {{first_name}}, {{event_name}} is {{event_when}}.{{slot_line}} Details: {{event_link}}',
    emailSubject: 'Reminder: {{event_name}} {{event_when}}',
    emailBody: 'Hey {{first_name}},\n\n{{event_name}} is {{event_when}} at {{event_place}}.{{slot_line}}\n\nStreet-legal, emissions-compliant trucks only on the dyno. Can’t make it? Call {{shop_phone}} so we can give your spot away.\n\nDetails: {{event_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_event_follow_up',
    name: 'Event follow-up',
    description: 'Day after an event: thanks attendees and shares their result card.',
    triggerEvent: 'community.event_follow_up',
    audience: 'customer',
    channels: ['email', 'sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: thanks for coming to {{event_name}}, {{first_name}}! {{result_line}} Book your next visit: {{booking_link}} Reply STOP to opt out.',
    emailSubject: 'Thanks for coming to {{event_name}}',
    emailBody: 'Hey {{first_name}},\n\nThanks for bringing your truck to {{event_name}}.{{result_line}}\n\nWant more out of it the right way? Book a visit: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'store_back_in_stock',
    name: 'Back-in-stock alert',
    description: 'Emails people who asked to hear when a part is back.',
    triggerEvent: 'community.back_in_stock',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Back in stock: {{product_title}}',
    emailBody: 'Good news — {{product_title}} is back in stock.\n\nGet it here: {{product_link}}\n\nYou asked us to tell you once. We won’t email about this part again.\n\n— Lucky Diesel',
  },
  {
    key: 'store_high_value_carts',
    name: 'Big carts left',
    description: 'Owner email listing store carts over $1,000 that didn’t turn into an order.',
    triggerEvent: 'community.high_value_carts',
    audience: 'owner',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: '{{cart_count}} big carts left yesterday ({{cart_total}})',
    emailBody: 'Store checkouts started but not finished in the last 24 hours:\n\n{{cart_lines}}\n\nKnown customers can be called from Contacts: {{admin_link}}',
  },
  {
    key: 'fleet_monthly_report',
    name: 'Fleet monthly report',
    description: 'First of the month: units serviced, spend and what’s due, to each fleet contact.',
    triggerEvent: 'community.fleet_monthly_report',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: '{{fleet_name}} fleet report — {{period}}',
    emailBody: 'Hi {{first_name}},\n\n{{report_text}}\n\nQuestions or trucks to schedule? Call {{shop_phone}}.\n\n— Lucky Diesel',
  },
  // ── CRM: speed-to-lead and pipeline (lib/marketing/core/crm-sweep.ts) ──
  {
    key: 'crm_sla_alert',
    name: 'Lead waiting (5 min)',
    description: 'Owner alert when a new lead hasn’t been contacted after the first SLA window.',
    triggerEvent: 'crm.sla_first',
    audience: 'owner',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lead waiting {{minutes}} min: {{customer_name}} ({{service}}, {{vehicle}}). Call {{customer_phone}}. {{admin_link}}',
  },
  {
    key: 'crm_sla_backup_alert',
    name: 'Lead waiting (backup)',
    description: 'Goes to the backup contact when a lead is still untouched after the second window.',
    triggerEvent: 'crm.sla_backup',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Still no reply after {{minutes}} min: {{customer_name}} ({{service}}). Call {{customer_phone}}. {{admin_link}}',
    emailSubject: 'Lead still waiting: {{customer_name}}',
    emailBody: '{{customer_name}} asked about {{service}} for a {{vehicle}} {{minutes}} minutes ago and hasn’t heard back.\n\nCall: {{customer_phone}}\nOpen: {{admin_link}}',
  },
  {
    key: 'crm_unanswered_alert',
    name: 'Unanswered text',
    description: 'Owner alert when a customer text sits without a reply.',
    triggerEvent: 'crm.unanswered',
    audience: 'owner',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'No reply in {{hours}}h to {{customer_name}}: "{{preview}}" {{admin_link}}',
  },
  {
    key: 'crm_follow_up_due',
    name: 'Snoozed follow-up due',
    description: 'Reminds the owner when a snoozed lead comes back.',
    triggerEvent: 'crm.follow_up_due',
    audience: 'owner',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Follow up today: {{customer_name}} ({{service}}). {{customer_phone}} {{admin_link}}',
  },
  {
    key: 'crm_hot_lead_alert',
    name: 'Hot lead',
    description: 'Owner alert when a lead’s score crosses the hot threshold.',
    triggerEvent: 'crm.hot_lead',
    audience: 'owner',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Hot lead ({{score}}): {{customer_name}}, {{service}} on a {{vehicle}}. {{customer_phone}} {{admin_link}}',
  },
  {
    key: 'crm_stale_deals_digest',
    name: 'Deals gone quiet',
    description: 'One email listing open deals with no activity for the stale window.',
    triggerEvent: 'crm.stale_deals',
    audience: 'owner',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: '{{count}} deals gone quiet',
    emailBody: 'No activity in {{hours}} hours:\n\n{{names}}\n\nWork the list: {{admin_link}}',
  },
  {
    key: 'crm_quote_expiry_nudge',
    name: 'Estimate expiring',
    description: 'Reminds the customer a few days before their estimate expires.',
    triggerEvent: 'crm.quote_expiring',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Hi {{first_name}}, your Lucky Diesel estimate for the {{vehicle}} is good until {{expires}}. Review it here: {{approval_link}} or call {{shop_phone}}.',
  },
  {
    key: 'mkt_lost_price_30d',
    name: 'Lost on price (30 days)',
    description: 'Lost-reason track: options that fit the budget, no price promises.',
    triggerEvent: 'crm.lost_price_30d',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Options for your {{vehicle}}',
    emailBody: 'Hey {{first_name}},\n\nBudget matters. There’s often more than one way to handle {{service}}, and we’re happy to walk through options and what can wait.\n\nBook a quick look: {{booking_link}} or call {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_lost_price_90d',
    name: 'Lost on price (90 days)',
    description: 'Lost-reason track: a seasonal check-in.',
    triggerEvent: 'crm.lost_price_90d',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: still thinking about {{service}} for your {{vehicle}}, {{first_name}}? Happy to talk options: {{booking_link}} Reply STOP to opt out.',
  },
  {
    key: 'mkt_lost_timing_30d',
    name: 'Lost on timing (30 days)',
    description: 'Lost-reason track: checks whether now is a better time.',
    triggerEvent: 'crm.lost_timing_30d',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: is now a better time for {{service}}, {{first_name}}? Grab a slot: {{booking_link}} Reply STOP to opt out.',
  },
  {
    key: 'mkt_lost_timing_90d',
    name: 'Lost on timing (90 days)',
    description: 'Lost-reason track: last timing check-in.',
    triggerEvent: 'crm.lost_timing_90d',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Ready when you are, {{first_name}}',
    emailBody: 'Hey {{first_name}},\n\nWhenever the {{vehicle}} is ready for {{service}}, we can get it in: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_lost_no_response_30d',
    name: 'Lost, no response (30 days)',
    description: 'Lost-reason track: one short check-in.',
    triggerEvent: 'crm.lost_no_response_30d',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Did we miss you?',
    emailBody: 'Hey {{first_name}},\n\nWe tried to reach you about {{service}}. If you still need help, reply here or book a time: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_lost_elsewhere_90d',
    name: 'Went elsewhere (90 days)',
    description: 'Lost-reason track: a friendly door-open note.',
    triggerEvent: 'crm.lost_elsewhere_90d',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Here if you need us',
    emailBody: 'Hey {{first_name}},\n\nHope the {{vehicle}} is running right. If you ever want a second opinion or need diesel work, we’re here: {{booking_link}} or {{shop_phone}}.\n\n— Lucky Diesel',
  },
];

/** Minutes are only used for display in the admin. */
export function describeTiming(definition: Pick<AutomationDefinition, 'anchor' | 'delayMinutes'>): string {
  const { anchor, delayMinutes } = definition;
  const amount =
    delayMinutes === 0
      ? ''
      : delayMinutes % DAY === 0
        ? `${delayMinutes / DAY} day${delayMinutes / DAY === 1 ? '' : 's'}`
        : delayMinutes % HOUR === 0
          ? `${delayMinutes / HOUR} hour${delayMinutes / HOUR === 1 ? '' : 's'}`
          : `${delayMinutes} min`;
  if (anchor === 'before_appointment') return `${amount} before appointment`;
  return amount ? `${amount} after` : 'Instantly';
}
