import type { Enums } from '@/lib/db/database.types';

/**
 * Default automations. Seeded into the `automations` table, where the owner
 * can toggle them and edit the wording. `key` is stable; code refers to it.
 *
 * Trigger events:
 *   lead.created · appointment.booked · work_order.status:<status> · inspection.sent
 *   estimate.approved · invoice.created · invoice.paid · daily.summary · service.due
 */
export interface AutomationDefinition {
  key: string;
  name: string;
  description: string;
  triggerEvent: string;
  audience: 'customer' | 'owner' | 'tech';
  channels: Enums<'message_channel'>[];
  anchor: 'event' | 'before_appointment';
  delayMinutes: number;
  sms?: string;
  emailSubject?: string;
  emailBody?: string;
}

const HOUR = 60;
const DAY = 24 * HOUR;

export const AUTOMATIONS: readonly AutomationDefinition[] = [
  // ── Leads ──
  {
    key: 'lead_owner_alert',
    name: 'New lead alert',
    description: 'Tell the owner the moment a service request comes in.',
    triggerEvent: 'lead.created',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "New lead: {{customer_name}} - {{vehicle}} - {{service}}. {{customer_phone}}. Open: {{admin_link}}",
    emailSubject: 'New service request — {{customer_name}} ({{service}})',
    emailBody:
      '{{customer_name}} just requested {{service}}.\n\nTruck: {{vehicle}}\nMileage: {{mileage}}\nPhone: {{customer_phone}}\nEmail: {{customer_email}}\n\n"{{details}}"\n\nOpen the lead: {{admin_link}}',
  },
  {
    key: 'lead_auto_reply',
    name: 'Lead auto-reply',
    description: 'Confirm the request instantly so the customer doesn’t call the next shop.',
    triggerEvent: 'lead.created',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Hey {{first_name}}, Lucky Diesel here. Got your {{service}} request for the {{vehicle}}. We'll reach out shortly. Reply STOP to opt out.",
    emailSubject: 'We got your request, {{first_name}}',
    emailBody:
      'Hey {{first_name}},\n\nThanks for reaching out about {{service}} for your {{vehicle}}. We’ll get back to you shortly with next steps.\n\nNeed us sooner? Call or text {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'lead_follow_up_1d',
    name: 'Lead follow-up (day 1)',
    description: 'If a lead hasn’t booked after a day, check in.',
    triggerEvent: 'lead.created',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: DAY,
    sms: "Hi {{first_name}}, still want to get the {{vehicle}} in for {{service}}? Book a time here: {{booking_link}}",
  },
  {
    key: 'lead_follow_up_3d',
    name: 'Lead follow-up (day 3)',
    description: 'Last friendly nudge before the lead goes cold.',
    triggerEvent: 'lead.created',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 3 * DAY,
    emailSubject: 'Still thinking about your {{vehicle}}?',
    emailBody:
      'Hey {{first_name}},\n\nJust following up on your {{service}} request. If you have questions about parts, tuning or pricing, reply to this email or call {{shop_phone}}.\n\nBook a time: {{booking_link}}\n\n— Lucky Diesel',
  },
  // ── Appointments ──
  {
    key: 'appointment_confirmation',
    name: 'Booking confirmation',
    description: 'Confirm the date and time as soon as it’s booked.',
    triggerEvent: 'appointment.booked',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "You're booked, {{first_name}}: {{service}} on {{appointment_time}}. See details in your portal: {{portal_link}}",
    emailSubject: 'Booked: {{service}} on {{appointment_time}}',
    emailBody:
      'Hey {{first_name}},\n\nYou’re on the schedule for {{service}} on {{appointment_time}}.\n\nYour portal: {{portal_link}}\n\nNeed to change it? Call or text {{shop_phone}}.\n\n— Lucky Diesel',
  },
  {
    key: 'booking_owner_alert',
    name: 'New booking alert',
    description: 'Tell the owner when someone books online.',
    triggerEvent: 'appointment.booked',
    audience: 'owner',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "New booking: {{customer_name}} - {{vehicle}} - {{service}} - {{appointment_time}}. {{admin_link}}",
  },
  {
    key: 'appointment_reminder_24h',
    name: 'Appointment reminder (24h)',
    description: 'Cut no-shows with a reminder the day before.',
    triggerEvent: 'appointment.booked',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'before_appointment',
    delayMinutes: DAY,
    sms: "Reminder: {{vehicle}} is booked at Lucky Diesel tomorrow, {{appointment_time}}. Reply C to confirm or call {{shop_phone}} to reschedule.",
  },
  {
    key: 'appointment_reminder_2h',
    name: 'Appointment reminder (2h)',
    description: 'A final heads-up on the day.',
    triggerEvent: 'appointment.booked',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'before_appointment',
    delayMinutes: 2 * HOUR,
    sms: "See you soon, {{first_name}}. Your {{service}} appointment is at {{appointment_time}}.",
  },
  // ── Work orders ──
  {
    key: 'job_checked_in',
    name: 'Truck checked in',
    description: 'Let the customer know work has started and where to follow along.',
    triggerEvent: 'work_order.status:in_progress',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Your {{vehicle}} is in the bay, {{first_name}}. Follow progress live: {{portal_link}}",
  },
  {
    key: 'inspection_ready',
    name: 'Inspection & estimate ready',
    description: 'Send the photo inspection and estimate for approval.',
    triggerEvent: 'inspection.sent',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "{{first_name}}, your inspection for the {{vehicle}} is ready: {{recommended_count}} items with photos, {{estimate_total}}. Review & approve: {{approval_link}}",
    emailSubject: 'Your {{vehicle}} inspection is ready to review',
    emailBody:
      'Hey {{first_name}},\n\nWe finished inspecting your {{vehicle}}. There are {{recommended_count}} recommended items totaling {{estimate_total}}, each with photos and notes.\n\nApprove or decline each item here: {{approval_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'estimate_nudge',
    name: 'Estimate approval nudge',
    description: 'If an estimate isn’t answered in 4 hours, send a gentle reminder.',
    triggerEvent: 'inspection.sent',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 4 * HOUR,
    sms: "Hi {{first_name}}, we're holding your {{vehicle}} until you review the estimate. Approve here: {{approval_link}} or call {{shop_phone}}.",
  },
  {
    key: 'estimate_decision_alert',
    name: 'Approval alert to shop',
    description: 'Tell the tech and owner the moment the customer approves.',
    triggerEvent: 'estimate.approved',
    audience: 'tech',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "WO #{{work_order}} approved by {{customer_name}}: {{approved_total}}. Good to go on the {{vehicle}}.",
  },
  {
    key: 'waiting_parts',
    name: 'Waiting on parts',
    description: 'Keep the customer in the loop when parts hold up a job.',
    triggerEvent: 'work_order.status:waiting_parts',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Update on your {{vehicle}}: we're waiting on parts. We'll text you as soon as they land. {{portal_link}}",
  },
  {
    key: 'job_ready',
    name: 'Truck ready for pickup',
    description: 'Pickup notice with the invoice and pay link.',
    triggerEvent: 'invoice.created',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Your {{vehicle}} is ready, {{first_name}}! Invoice {{invoice_total}}. Pay online to skip the counter: {{pay_link}}",
    emailSubject: 'Your {{vehicle}} is ready — invoice #{{invoice_number}}',
    emailBody:
      'Hey {{first_name}},\n\nYour {{vehicle}} is done and ready for pickup.\n\nInvoice #{{invoice_number}}: {{invoice_total}}\nPay online: {{pay_link}}\n\nWork details, photos and your truck’s history are in your portal: {{portal_link}}\n\n— Lucky Diesel',
  },
  // ── After the job ──
  {
    key: 'payment_receipt',
    name: 'Payment receipt',
    description: 'Receipt and thanks as soon as an invoice is paid.',
    triggerEvent: 'invoice.paid',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Receipt for invoice #{{invoice_number}}',
    emailBody:
      'Thanks, {{first_name}}.\n\nWe received your payment of {{invoice_total}} for invoice #{{invoice_number}} ({{vehicle}}).\n\nYour full service record is in your portal: {{portal_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'review_request',
    name: 'Google review request',
    description: 'Asks every customer for a review the day after pickup. No filtering, per Google policy.',
    triggerEvent: 'invoice.paid',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: DAY,
    sms: "Thanks for trusting us with the {{vehicle}}, {{first_name}}. Mind sharing how it went? {{review_link}}",
  },
  {
    key: 'review_reminder',
    name: 'Review reminder',
    description: 'One reminder, three days later, only if they haven’t been asked again.',
    triggerEvent: 'invoice.paid',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 4 * DAY,
    emailSubject: 'How’s the {{vehicle}} running?',
    emailBody:
      'Hey {{first_name}},\n\nHope the truck is running strong. If you have a minute, a Google review helps other diesel owners find us: {{review_link}}\n\nAnything not right? Reply here and it comes straight to the owner.\n\n— Lucky Diesel',
  },
  {
    key: 'service_due',
    name: 'Service due reminder',
    description: 'Brings customers back when maintenance or a tune check is due.',
    triggerEvent: 'service.due',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Hey {{first_name}}, the {{vehicle}} is due for {{due_service}}. Grab a time: {{booking_link}}",
  },
  {
    key: 'declined_work_follow_up',
    name: 'Declined work follow-up',
    description: '30 days after an item is declined, remind the customer it’s still recommended.',
    triggerEvent: 'estimate.approved',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 30 * DAY,
    emailSubject: 'Still on the list for your {{vehicle}}',
    emailBody:
      'Hey {{first_name}},\n\nLast visit we recommended: {{declined_items}}. Want to get it taken care of? Book here: {{booking_link}}\n\n— Lucky Diesel',
  },
  // ── Owner ──
  {
    key: 'daily_summary',
    name: 'Owner daily summary',
    description: '7am email: today’s schedule, new leads, open estimates and unpaid invoices.',
    triggerEvent: 'daily.summary',
    audience: 'owner',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Lucky Diesel today: {{appointments_today}} appointments, {{new_leads}} new leads',
    emailBody:
      'Good morning.\n\nToday: {{appointments_today}} appointments\nIn the shop: {{open_jobs}} open jobs\nNew leads (24h): {{new_leads}}\nWaiting on approval: {{awaiting_approval}}\nUnpaid invoices: {{unpaid_total}}\nRevenue this week: {{week_revenue}}\n\nDashboard: {{admin_link}}',
  },
  // ── Marketing lifecycle (lib/marketing/core/lifecycle.ts emits these daily) ──
  // Keys starting with `mkt_` are promotional: sendMessage applies marketing
  // consent, suppressions, weekly caps and 8am–9pm quiet hours to them.
  {
    key: 'mkt_win_back_6m',
    name: 'Win-back (6 months)',
    description: 'Six months since the last paid visit and nothing booked: invite them back.',
    triggerEvent: 'marketing.win_back_6m',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel here, {{first_name}}. It's been about 6 months since we saw {{vehicle}}. Due for {{due_service}}? Book: {{booking_link}} Reply STOP to opt out.",
  },
  {
    key: 'mkt_win_back_12m',
    name: 'Win-back (12 months)',
    description: 'A year without a visit: a personal note from the shop.',
    triggerEvent: 'marketing.win_back_12m',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Been a while, {{first_name}}',
    emailBody:
      'Hey {{first_name}},\n\nIt’s been about a year since {{vehicle}} was in the shop. A yearly once-over catches small leaks, worn filters and fuel system issues before they strand you.\n\nGrab a time that works: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_tune_follow_up',
    name: 'Post-tune check-in',
    description: 'Three days after a tune: any codes, regens or drivability questions?',
    triggerEvent: 'marketing.tune_follow_up',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel checking in, {{first_name}}. How is {{vehicle}} running since the tune? Any codes or questions, reply here. We offer {{due_service}} anytime.",
  },
  {
    key: 'mkt_dyno_recheck',
    name: 'Dyno re-check offer',
    description: 'About a month after a tune, offer a re-check pull and datalog review.',
    triggerEvent: 'marketing.dyno_recheck',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: {{first_name}}, it's been a month on the tune. Want {{due_service}} to confirm {{vehicle}} is dialed in? {{booking_link}} Reply STOP to opt out.",
  },
  {
    key: 'mkt_seasonal_towing',
    name: 'Towing season prep',
    description: 'Spring (Mar–mid Apr): pre-season towing inspection for boat and camper season.',
    triggerEvent: 'marketing.seasonal.towing_season',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: boat and camper season is close, {{first_name}}. Book {{due_service}} for {{vehicle}}: trans, cooling, brakes. {{booking_link}} Reply STOP to opt out.",
    emailSubject: 'Ready to tow this season?',
    emailBody:
      'Hey {{first_name}},\n\nTowing season is almost here. Before the first trip to the ramp, we’ll check transmission fluid and temps, cooling system, brakes and trailer wiring on {{vehicle}}.\n\nBook {{due_service}}: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_hurricane',
    name: 'Hurricane season readiness',
    description: 'Late May: evacuation-ready truck check. Service reminder tone, no crisis selling.',
    triggerEvent: 'marketing.seasonal.hurricane_prep',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Is your truck evacuation-ready?',
    emailBody:
      'Hey {{first_name}},\n\nHurricane season starts June 1. If you ever need to leave in a hurry or tow family and gear inland, {{vehicle}} should be ready: fuel filters, batteries, cooling system and tires.\n\nBook {{due_service}}: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_seasonal_winter',
    name: 'Winter diesel prep',
    description: 'Mid Oct–Nov: cold starts, batteries, glow plugs/grid heater and anti-gel before trips north.',
    triggerEvent: 'marketing.seasonal.winter_diesel',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Heading north or hunting inland this winter?',
    emailBody:
      'Hey {{first_name}},\n\nCharleston rarely gels, but a cold morning up the road can. Before winter trips we check batteries, glow plugs or grid heater, fuel filters and add anti-gel treatment.\n\nBook {{due_service}} for {{vehicle}}: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_birthday',
    name: 'Birthday note',
    description: 'Only for customers who volunteered a birthday.',
    triggerEvent: 'marketing.birthday',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Happy birthday, {{first_name}}',
    emailBody: 'Hey {{first_name}},\n\nHappy birthday from everyone at Lucky Diesel. Thanks for trusting us with {{vehicle}}.\n\nNext time you’re in, mention your birthday month and the coffee’s on us.\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_customer_anniversary',
    name: 'Customer anniversary',
    description: 'Yearly thank-you on the date of the first paid visit.',
    triggerEvent: 'marketing.customer_anniversary',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Thanks for {{due_service}}',
    emailBody: 'Hey {{first_name}},\n\nToday marks {{due_service}}. We appreciate you trusting us with {{vehicle}}.\n\nIf it’s been a while, book a check-up: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_build_plan_follow_up',
    name: 'Build plan follow-up',
    description: 'Planner quote requests with no booking after 5 days.',
    triggerEvent: 'marketing.build_plan_abandoned',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Still planning the {{vehicle}} build?',
    emailBody:
      'Hey {{first_name}},\n\nYou put together a build plan with us last week. Happy to walk through parts, install time and pricing, or break it into stages that fit the budget.\n\nReply to this email, call {{shop_phone}}, or book a consult: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_store_checkout_follow_up',
    name: 'Parts checkout follow-up',
    description: 'Shopify has no abandoned-checkout webhook, so this uses our store checkout-click event (consented contacts only).',
    triggerEvent: 'marketing.store_checkout_click',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Want us to install those parts?',
    emailBody:
      'Hey {{first_name}},\n\nLooks like you were checking out parts on our store. If you have fit questions, or want us to install them on {{vehicle}}, reply here or book an install: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_referral_thank_you',
    name: 'Referral thank-you',
    description: 'Thanks the referrer as soon as a friend uses their code.',
    triggerEvent: 'marketing.referral_created',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: thanks for sending a friend our way, {{first_name}}! You'll get {{due_service}} once their first job is done. Reply STOP to opt out.",
  },
  {
    key: 'mkt_referral_reward',
    name: 'Referral reward earned',
    description: 'Tells the referrer their reward is ready after the friend’s first paid job.',
    triggerEvent: 'marketing.referral_rewarded',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: your referral paid off, {{first_name}}. {{due_service}} is on your account for your next visit. Reply STOP to opt out.",
    emailSubject: 'Your referral reward is ready',
    emailBody: 'Hey {{first_name}},\n\nYour friend’s first job is done, so {{due_service}} is now on your account. It applies automatically at your next visit.\n\nThanks for spreading the word.\n\n— Lucky Diesel',
  },
  {
    key: 'review_detractor_follow_up',
    name: 'Unhappy feedback follow-up',
    description: 'Private service recovery after a low survey score (the owner alert is content_nps_low_score_alert). The Google review link still goes to everyone; nothing is gated or suppressed.',
    triggerEvent: 'marketing.review_detractor',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "{{first_name}}, thank you for the honest feedback. The owner of Lucky Diesel will call you personally to make it right. You can also reach us at {{shop_phone}}.",
  },
  {
    key: 'mkt_fleet_pm_reminder',
    name: 'Fleet PM reminder',
    description: 'Weekly digest to the fleet manager when units are due by miles or days.',
    triggerEvent: 'marketing.fleet_pm_due',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: 'Fleet maintenance due: {{due_service}}',
    emailBody:
      'Hi {{first_name}},\n\nThese units are due for preventive maintenance: {{due_service}}.\n\nReply with the days that work and we’ll batch them to keep trucks on the road, or book here: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'mkt_dyno_day_invite',
    name: 'Dyno day invite',
    description: 'Invites tuned-truck owners 1–3 weeks before a dyno day.',
    triggerEvent: 'marketing.dyno_day_invite',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Lucky Diesel: {{first_name}}, you're invited to {{due_service}}. Bring {{vehicle}} and see what it makes. Details: {{booking_link}} Reply STOP to opt out.",
    emailSubject: 'You’re invited: {{due_service}}',
    emailBody:
      'Hey {{first_name}},\n\nWe’re hosting {{due_service}} at the shop. Bring {{vehicle}}, make a pull and hang out with other diesel owners. Only street-legal, emissions-compliant trucks on the dyno.\n\nSave a spot: {{booking_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'missed_call_text_back',
    name: 'Missed-call text-back',
    description: 'Texts a caller within a minute when a call goes unanswered. Sent by the Twilio voice webhook, not by emit.',
    triggerEvent: 'call.missed',
    audience: 'customer',
    channels: ['sms'],
    anchor: 'event',
    delayMinutes: 0,
    sms: "Sorry we missed your call, this is Lucky Diesel. We're under a truck right now. How can we help? Reply here or book online: {{booking_link}}",
  },
  // ── Marketing content (part B): sent by lib/marketing/content, not by emit ──
  {
    key: 'content_review_negative_alert',
    name: 'Negative review alert',
    description: 'Tells the owner right away when a 1–3 star review comes in, with a drafted reply waiting for approval.',
    triggerEvent: 'marketing.review_negative',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: new {{rating}}-star review from {{author}} on {{source}}. A reply draft is waiting: {{admin_link}}',
    emailSubject: '{{rating}}-star review from {{author}}',
    emailBody:
      '{{author}} left a {{rating}}-star review on {{source}}:\n\n"{{review_text}}"\n\nA reply draft is waiting for your approval (nothing posts without you): {{admin_link}}',
  },
  {
    key: 'content_nps_survey',
    name: 'Post-job survey (NPS)',
    description: '3 days after a paid job: a 0–10 survey plus the Google review link for everyone. Scores never decide who gets the link.',
    triggerEvent: 'marketing.nps_request',
    audience: 'customer',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 3 * DAY,
    sms: 'Lucky Diesel: how likely are you to recommend us, 0–10? {{nps_link}} Reviews help too: {{review_link}} Reply STOP to opt out.',
    emailSubject: 'How did we do on the {{vehicle}}?',
    emailBody:
      'Hey {{first_name}},\n\nOne quick question: how likely are you to recommend Lucky Diesel to a friend, 0–10?\n{{nps_link}}\n\nIf you have a minute, a Google review helps other diesel owners find us: {{review_link}}\n\n— Lucky Diesel',
  },
  {
    key: 'content_nps_low_score_alert',
    name: 'Low survey score alert',
    description: 'Tells the owner when a survey score is 0–6 so they can call the customer.',
    triggerEvent: 'marketing.nps_low_score',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: {{customer_name}} scored us {{score}}/10. "{{comment}}" Call them: {{customer_phone}}',
    emailSubject: 'Low survey score from {{customer_name}} ({{score}}/10)',
    emailBody: '{{customer_name}} scored us {{score}}/10.\n\nComment: "{{comment}}"\n\nPhone: {{customer_phone}}\nThey still received the review link, as every customer does.',
  },
  {
    key: 'content_drafts_ready',
    name: 'Marketing drafts ready',
    description: 'Emails the owner when new ads, posts or replies are waiting for approval.',
    triggerEvent: 'marketing.drafts_ready',
    audience: 'owner',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: '{{count}} marketing drafts waiting for you',
    emailBody: 'New drafts are ready: {{summary}}\n\nNothing publishes until you approve it: {{admin_link}}',
  },
  {
    key: 'content_campaign_paused',
    name: 'Ad campaign auto-paused',
    description: 'Tells the owner when a budget guard pauses an ad campaign.',
    triggerEvent: 'marketing.campaign_paused',
    audience: 'owner',
    channels: ['sms', 'email'],
    anchor: 'event',
    delayMinutes: 0,
    sms: 'Lucky Diesel: ad campaign "{{campaign}}" was paused ({{reason}}). {{admin_link}}',
    emailSubject: 'Paused: {{campaign}}',
    emailBody: 'The budget guard paused "{{campaign}}" because {{reason}}.\n\nReview it before turning it back on: {{admin_link}}',
  },
  {
    key: 'content_lead_magnet_delivery',
    name: 'Lead magnet delivery',
    description: 'Emails the requested checklist straight away.',
    triggerEvent: 'marketing.lead_magnet',
    audience: 'customer',
    channels: ['email'],
    anchor: 'event',
    delayMinutes: 0,
    emailSubject: '{{magnet_title}}',
    emailBody: 'Hey {{first_name}},\n\nHere’s your {{magnet_title}}.\n\n{{magnet_body}}\n\nWant us to handle it? Book a bay: {{booking_link}} or call {{shop_phone}}.\n\n— Lucky Diesel',
  },
];

/** Minutes are only used for display in the admin. */
export function describeTiming(definition: Pick<AutomationDefinition, 'anchor' | 'delayMinutes'>): string {
  const { anchor, delayMinutes } = definition;
  const amount =
    delayMinutes === 0
      ? ''
      : delayMinutes % DAY === 0
        ? `${delayMinutes / DAY} day${delayMinutes / DAY === 1 ? '' : 's'}`
        : delayMinutes % HOUR === 0
          ? `${delayMinutes / HOUR} hour${delayMinutes / HOUR === 1 ? '' : 's'}`
          : `${delayMinutes} min`;
  if (anchor === 'before_appointment') return `${amount} before appointment`;
  return amount ? `${amount} after` : 'Instantly';
}
